import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import clsx from "clsx";
import Nav from "./components/nav/Nav";
import Footer from "./components/footer/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={clsx("root-layout", "flex flex-col min-h-screen")}>
          <Nav />
          <main
            className={clsx(
              "main-layout",
              "border border-green-500 flex-1 flex flex-col items-center w-full"
            )}
          >
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
